language: generic 
sudo: required
services:
  - docker

#set of commands to be executed before the test runs
before_install:
  - docker build -t feven2020/react-test -f ./client/Dockerfile.dev ./client

#script section contains all the commands that needs to be executed
script:
  - docker run -e CI=true feven2020/react-test npm test 

#after successfull test
after_success:
  - docker build -t feven2020/multi-client ./client
  - docker build -t feven2020/multi-nginx ./nginx
  - docker build -t feven2020/multi-server ./server
  - docker build -t feven2020/multi-worker ./worker
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take those images and push them to docker hub
  - docker push feven2020/multi-client
  - docker push feven2020/multi-nginx
  - docker push feven2020/multi-server
  - docker push feven2020/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-127919176286'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    